### ISSUE TITLE
Implement KPI-2-0

### ISSUE THREAD

**Issue by jbianchi81** [wmo-im/pywmdr#5]
Implement KPI-2-0: Station characteristics as described in [https://github.com/wmo-im/wmdr/blob/issue42/kpi/2-0.adoc](https://github.com/wmo-im/wmdr/blob/issue42/kpi/2-0.adoc)

**Comment by jbianchi81** [comment]
On 2-0-02 a reference to a code list of time zones is required, which is missing. Also, a static map or web API to get the timezone of a geographic point is required. This issue is addressed [here](https://github.com/wmo-im/wmds/issues/339). Temporarily, [this](https://github.com/evansiroky/timezone-boundary-builder) is being used.

**Comment by jbianchi81** [comment]
Same issue with 2-0-12-b, but on the schema a "EventType" code list is referred while in codes.wmo.int there isn't a list with that name but there is a "EventAtFacility" ([http://codes.wmo.int/wmdr/_EventAtFacility](http://codes.wmo.int/wmdr/_EventAtFacility)). Using that one.

**Comment by jbianchi81** [comment]
On 20-0-12-c logEntry/description maybe we should set a minimum length for the string. Temporarily set at 100 characters

**Comment by jbianchi81** [comment]
Timezones codelist check implemented (https://github.com/wmo-im/pywmdr/commit/7da610a9e516f703c2ede843a1a1943b927e78f2) based on the WMDR proposal: https://github.com/wmo-im/wmds/blob/issue339/tables_en/4-08.csv discussion here: https://github.com/wmo-im/wmds/issues/339

**Comment by ferrighi** [comment]
I'm getting No module named 'pywmdr.timezone_codelist'. Could it be you have forgotten to push the file timezone_codelist.py?

**Comment by jbianchi81** [comment]
Indeed! Now it's here: https://github.com/wmo-im/pywmdr/blob/first-draft/pywmdr/timezone_codelist.py .
