### ISSUE TITLE
Implementation of KPI-5-0: Bibliographic references and Documents (OSCAR/Surface)

### ISSUE THREAD

**Issue by jbianchi81** [wmo-im/pywmdr#7]

**Comment by jbianchi81** [comment]
This KPI can only be implemented within OSCAR/Surface because it relates with a OSCAR/Surface specific metadata element (not a part of WMDR) (see [https://github.com/wmo-im/wmdr/issues/42#issuecomment-946443888](https://github.com/wmo-im/wmdr/issues/42#issuecomment-946443888))

**Comment by ferrighi** [comment]
I have added all the oscar-dependent kpis to the list of kpis with output:
{
    "kpi_50": {
        "name": "KPI-5-0: Bibliographic references and Documents (OSCAR/Surface)",
        "total": 0,
        "score": 0,
        "comments": [
            "not implemented"
        ],
        "percentage": null
    }
}
